server:
  port: 8080
  mode: "debug"

database:
  host: "localhost"
  port: 3306
  user: "root"
  password: "your-password"
  dbname: "synapse"
  charset: "utf8mb4"
  max_open_conns: 100
  max_idle_conns: 10

jwt:
  secret: "your-secret-key"
  expire_hours: 72

log:
  level: "info"
  path: "./storage/logs/app.log"